config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to:"pages#about"
  get "signup", to:"users#new"
  resources :users, except:[:new]

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence:true, length:{minimum:3, maximum:50}
	validates :description, presence: true, length:{minimum:10, maximum:300}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles
	before_save { self.email = email.downcase }
	validates :username,presence: true, uniqueness: {case_sensitive: false}, 
			  length:{minimum:3, maximum:25}
	VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
	validates :email, presence: true, length: {maximum: 105},
		      uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only:[:edit,:update,:show,:destroy] 
	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		#render plain: params[:article].inspect	
		debugger
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:success] = "Article was successfully created."
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article was successfully updated."
			redirect_to article_path(@article)
		else
			render 'edit'
		end

	end

	def destroy
		@article.destroy
		flash[:danger] = "Article was successfully deleted."
		redirect_to articles_path
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end
		def article_params
			params.require(:article).permit(:title,:description)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home

	end

	def about

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        flash[:success] = "Welcome to the Harits Blog #{@user.username}"
        redirect_to articles_path
      else
        render 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= render "shared/errors", obj:@article %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html=>{class: "form-horizontal",role:"form"}) do |f| %>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :title %>
			</div>
			<div class="col-sm-8">
				<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :description %>
			</div>
			<div class="col-sm-8">
				<%= f.text_area :description, class: "form-control", rows:"10", placeholder: "Body of the article" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class:"btn btn-primary btn-lg" %>
			</div>
		</div>

		<% end %>
		<div class="col-xs-4 col-xs-offset-5">
			[<%= link_to "Return to articles Listing", articles_path %>]
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit Existing Article.</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 class="text-center">Listing all Articles</h1>


<% @articles.each do |article| %>
<div class="row">
	<div class="well col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				<%= link_to article.title, article_path(article) %>
			</div>
			<div class="article-body">
				<%= truncate(article.description, length: 100) %>
				<div class="article-meta-details">
					<small>Created By: <%= article.user.username if article.user %>,
						<%= time_ago_in_words(article.created_at) %> ago,
						last Updated: <%= time_ago_in_words(article.updated_at) %> ago
					</small>
				</div>
			</div>
			<div class="article-actions">
				<%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
				<%= link_to "Delete this Article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article? "}, class: "btn btn-xs btn-danger" %>  
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center">Create new Article Here.</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 class="text-center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="text-center description"><strong>Description: </strong></h4>
	<hr/>
	<%= simple_format(@article.description) %>
	<div class="article-actions">
		<%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
		<%= link_to "Delete this Article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article? "}, class: "btn btn-xs btn-danger" %>  
		<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; The complete Ruby on Rails site by <a href="#">Haritsinh Gohil</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "about" ,about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name,msg| %>
		<div class='alert alert-<%="#{name}"%>'>
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id =>"flash#{name}" if msg.is_a?(String) %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Harits blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is Alpha Blog about page.</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
	<h1 class="white-color">HARITS BLOG</h1>
	<%= link_to "Sign up now", "#", class: "btn btn-danger btn-lg btn-xlg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					prohibited this article from being saved.
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="text-center"> Sign up for Harits Blog </h1>

<%= render "shared/errors", obj:@user %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html=>{class: "form-horizontal",role:"form"}) do |f| %>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :username %>
			</div>
			<div class="col-sm-8">
				<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :email %>
			</div>
			<div class="col-sm-8">
				<%= f.email_field :email, class: "form-control", placeholder: "Enter Email" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-2 control-label">
				<%= f.label :password %>
			</div>
			<div class="col-sm-8">
				<%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit "Sign up", class:"btn btn-primary btn-lg" %>
			</div>
		</div>

		<% end %>
		<div class="col-xs-4 col-xs-offset-5">
			[<%= link_to "Return to articles Listing", articles_path %>]
		</div>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>